Removed libc dependency this seems to be exported from core (or atleast is not required to run on OSX).  I am inexperienced with the swift package manager but this was the quickest way to remove the following error
error: multiple modules with the name libc found
fix: modules should have a unique name across dependencies

The vapor executable is built and appears to run fine at least on OSX.